stages:
  - sonar
  - build
  - deploy

SonarScan:
   stage: sonar
   image: 
     name: sonarsource/sonar-scanner-cli:latest
     entrypoint: [""] 
   variables: 
     SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
     GIT_DEPTH: "0"
   allow_failure: true  
   cache:
     key: "${CI_JOB_HOME}" 
     paths: 
       - sonar/cache
   script:
     - git whatchanged -n 1
     - if [[ "$(git whatchanged -n 1 | grep 'tenant-config-service')" ]]; then cd tenant-config-service && sonar-scanner -X -Dsonar.sources=.tenant-config-service -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD;else echo "error"; fi
   only:
     - main

Build:
   stage: build
   image: docker:18.09.7-dind
   services:
      - docker:18.09.7-dind
   variables:
      DOCKER_DRIVER: overlay
   script:
     - apk add --no-cache git 
     - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
     - export DOCKER_HOST=tcp://localhost:2375
     - docker build -t registry.neosoftcloud.org/kirti.mandwade/search-as-service . && docker push registry.neosoftcloud.org/kirti.mandwade/search-as-service
   only:
     - main

Deploy:
  stage: deploy
  image: amazon/aws-cli
  script:
    - yum install git -y
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - mkdir ~/.kube
    - cat $KUBE_CONFIG > ~/.kube/config
    - kubectl rollout restart deploy/search-as-service -n coe-search
  only:
    - main