apiVersion: v1
kind: Service
metadata:
  name: search-service-ingress-service
spec:
  selector:
    app: search-service-ingress
  ports:
    - protocol: 'TCP'
      port: 8081
      targetPort: 8081
  type: LoadBalancer