apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: solr1-container
  name: solr1-container
spec:
  ports:
    - name: "8981"
      port: 8981
      targetPort: 8983
  selector:
    io.kompose.service: solr1-container
status:
  loadBalancer: {}
