apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: zoo1
  name: zoo1
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
    - name: "7001"
      port: 7001
      targetPort: 7000
  selector:
    io.kompose.service: zoo1
status:
  loadBalancer: {}
