apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: zoo2
  name: zoo2
spec:
  ports:
    - name: "2182"
      port: 2182
      targetPort: 2181
    - name: "7002"
      port: 7002
      targetPort: 7000
  selector:
    io.kompose.service: zoo2
status:
  loadBalancer: {}
