apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: zoo3
  name: zoo3
spec:
  ports:
    - name: "2183"
      port: 2183
      targetPort: 2181
    - name: "7003"
      port: 7003
      targetPort: 7000
  selector:
    io.kompose.service: zoo3
status:
  loadBalancer: {}
